### PR TITLE
Persist tab order on per-project basis between close/open.

### LINKED ISSUE #4416: Keep manual sorting of open files when reopening project
### Apache NetBeans version

Apache NetBeans 14

### What happened

In the settings, Appearance > Document Tabs > Sort nothing. I work in a project and arrange files in the tabs panel as I see fit. If I close the netbins program, they will open in the same order that I sorted them manually. But if I close the project in the program and then reopen it, then the manual arrangement of the files changes to a messy one.

This happens both in the latest version and in the previous ones (13, 12.x and earlier), it also happens in Windows and Ubuntu

### How to reproduce

Open project.
Open its files (10 pieces) and set their order yourself as convenient.
Close the project (**not Netbeans**), open the project again.
The order of files in tabs is changed.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 7 10, Ubuntu 18.04-21.10

### JDK

16 and earler

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

_No response_

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

### PR DESCRIPTION
**Pull request by mbien**
- changed to collections which retain entry order
 - refresh storage on close if order changes

note:

 - opened files are stored per project, re-opening multiple projects will restore the right order within the project but they will be grouped by project as side effect.
 - opened projects might not have a deterministic order since they come right from the lookup (was not the focus of this PR)

fixes #4416

### CODE REVIEW

File: ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java [hunk 1]
```diff
@@ -598,12 +596,12 @@ public static Set<FileObject> openProjectFiles (Project p, Group grp) {
         return toRet;
     }
     
-    private static Set<String> getOpenFilesUrls(Project p, String groupName) {
+    private static List<String> getOpenFilesUrls(Project p, String groupName) {
```
Comment (eirikbakke) [inline ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java:599]: Is there any reason to switch the types from Set to List (here and other places)? If for some reason the old code relied on Set removing duplicate entries, then those duplicates will now start appearing.

(Ideally there'd be an "OrderedSet" type, but there is not.)

In general I'm a fan of always just using LinkedHashSet instead of HashSet, except if there are huge performance benefits to HashSet (very rare, in fact it's faster to iterate over a LinkedHashSet than a HashSet). Since HashSet gives an undefined order, it is always safe to replace HashSet with LinkedHashSet. But switching Set to List can change behavior.

Comment (mbien) [reply ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java:599]: reason was iteration convenience since two collections had to be compared index by index. I do agree that List vs Set is a statement in itself.

I did also wonder which methods were meant to reduplicate and which were not and planned to give this another pass while checking for that aspect.

This might stay a list (due to convenience) - but a reduplicated one. (will also add a comment).

Comment (mbien) [reply ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java:599]: Right, i did think about this while making the changes - but I didn't know the spec and there were no comments in code.

So what I likely will end up doing is to send a deduplicated list back + add a comment. This has probably the lowest risk of not breaking anything since the old behavior would be similar.

Comment (eirikbakke) [reply ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java:599]: @neilcsmith-net Oh that's true. I think either retaining the duplication or keeping only the first occurrence would be fine. But would be a good case to test, just to see that nothing breaks.

> This might stay a list (due to convenience) - but a reduplicated one. (will also add a comment).

Yeah, sure. (I assume you meant "de"duplicated.)

File: ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java [hunk 2]
```diff
@@ -483,31 +481,31 @@ public static boolean closeAllDocuments(Project[] projects, boolean notifyUI, St
...
-        Set<String> openFileUrls = getOpenFilesUrls(p, groupName);
-        if(urls.isEmpty() && openFileUrls.isEmpty()) {
+        List<String> openFileUrls = getOpenFilesUrls(p, groupName);
+        if (urls.isEmpty() && openFileUrls.isEmpty()) {
             // was empty, stays empty, leave
             return;                
-        }        
-        if(urls.size() == openFileUrls.size()) {
+        }
+        // check if file list changed, order matters
```
Comment (eirikbakke) [inline ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java:499]: Why not just urls.equals(openFileUrls)?

That works now that the two are List<String> instead of Set<String>.

File: ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java (hunk 1 above)
Comment (mbien) [reply ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java:599]: btw how can I open the same file twice

File: ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java (hunk 2 above)
Comment (mbien) [reply ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java:494]: good point - simplified the section

File: ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java (hunk 1 above)
Comment (neilcsmith-net) [reply ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java:587]: Tab menu, "clone" IIRC.

**Review by eirikbakke — APPROVED** [review]

**Comment by mbien** [comment]
thanks for review. going to merge since I found an ergonomics related NPE in the same area which can be fixed in a followup PR
