### PR TITLE
Avoid using an invalid JavaPlatform

### LINKED ISSUE #4651: Java hints disabled by exception; Java Platforms has bad entry
### Apache NetBeans version

Apache NetBeans 15

### What happened

No hint highlights after exception in hints processing

### How to reproduce

(These steps reproduce 100% for me. I can provide the project and tainted userdir if that would be useful)

I narrowed down the issue with these steps. Once there's a userdir that has the problem, just start NB and get the exception
- staring with clean .nb/15 (some -J-D added to netbeans.conf)
- start nb, no imports
- open project, java file; note visible hints highlights
  (not all projects exhibit the problem)
- import from "tainted userdir", restart
    categories: general, miscellaneous (need both)
- OBSERVE: no hints, exception (see below)

In Java Platform Manager there are several entries, the entry `Zulu 18.0.2.1+1`
is shown in red. Select it and the following for PlatformInstallFolder:
```
/junk/Downloads/zulu18.32.13-ca-jdk18.0.2.1-linux_x64/zulu18.32.13-ca-jdk18.0.2.1-linux_x64
```
is displayed in red, and there's the message `Error: the specified folder does not contain a java platform`
Restart NB and the problem persists.
Remove this bad entry, and the hints show up again.

NOTE: the project does not reference this JDK.

I wonder if Platform is providing garbage to HintProcessing, or if HintProcessing is not handling a valid return from Platform.

I can see how importing miscellaneous is required, I wonder what's in General that's needed to trigger it.

FYI: While doing some cleanup I moved the referenced directory to where all the jdk's on this system reside, and forgot about it. Several days later, after changing and moving around lots of stuff locally, I noticed there was a hints problem.

```
SEVERE [org.openide.util.Exceptions]
java.lang.NullPointerException
	at com.sun.tools.javac.code.Types$ImplementationCache.implementationInternal(Types.java:2983)
	at com.sun.tools.javac.code.Types$ImplementationCache.get(Types.java:2969)
	at com.sun.tools.javac.code.Types.implementation(Types.java:3004)
	at com.sun.tools.javac.comp.Check.checkClassOverrideEqualsAndHash(Check.java:2199)
	at com.sun.tools.javac.comp.Check.checkClassOverrideEqualsAndHashIfNeeded(Check.java:2189)
	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5389)
	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5210)
	at com.sun.tools.javac.comp.Attr.attrib(Attr.java:5155)
	at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1317)
	at org.netbeans.modules.java.hints.spiimpl.Utilities.constructScope(Utilities.java:775)
	at org.netbeans.modules.java.hints.declarative.Hacks.constructScope(Hacks.java:73)
	at org.netbeans.modules.java.hints.declarative.DeclarativeHintsParser.lambda$resolve$0(DeclarativeHintsParser.java:494)
	at org.netbeans.modules.java.source.parsing.MimeTask.run(MimeTask.java:60)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callUserTask(TaskProcessor.java:586)
	at org.netbeans.modules.parsing.api.ParserManager$MimeTaskAction.run(ParserManager.java:364)
	at org.netbeans.modules.parsing.api.ParserManager$MimeTaskAction.run(ParserManager.java:347)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:181)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:178)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:178)
	at org.netbeans.modules.parsing.api.ParserManager.parse(ParserManager.java:318)
	at org.netbeans.api.java.source.JavaSource.runUserActionTaskImpl(JavaSource.java:433)
	at org.netbeans.api.java.source.JavaSource.runUserActionTask(JavaSource.java:425)
	at org.netbeans.modules.java.hints.declarative.DeclarativeHintsParser.resolve(DeclarativeHintsParser.java:473)
	at org.netbeans.modules.java.hints.declarative.DeclarativeHintsParser.access$000(DeclarativeHintsParser.java:80)
	at org.netbeans.modules.java.hints.declarative.DeclarativeHintsParser$Impl.parseCondition(DeclarativeHintsParser.java:307)
	at org.netbeans.modules.java.hints.declarative.DeclarativeHintsParser$Impl.parseConditions(DeclarativeHintsParser.java:254)
	at org.netbeans.modules.java.hints.declarative.DeclarativeHintsParser$Impl.parseRule(DeclarativeHintsParser.java:211)
	at org.netbeans.modules.java.hints.declarative.DeclarativeHintsParser$Impl.parseInput(DeclarativeHintsParser.java:180)
	at org.netbeans.modules.java.hints.declarative.DeclarativeHintsParser$Impl.access$200(DeclarativeHintsParser.java:87)
	at org.netbeans.modules.java.hints.declarative.DeclarativeHintsParser.parse(DeclarativeHintsParser.java:391)
	at org.netbeans.modules.java.hints.declarative.DeclarativeHintRegistry.parseHints(DeclarativeHintRegistry.java:255)
	at org.netbeans.modules.java.hints.declarative.DeclarativeHintRegistry.parseHintFile(DeclarativeHintRegistry.java:233)
	at org.netbeans.modules.java.hints.declarative.DeclarativeHintRegistry.readHints(DeclarativeHintRegistry.java:122)
	at org.netbeans.modules.java.hints.declarative.DeclarativeHintRegistry.computeHints(DeclarativeHintRegistry.java:105)
	at org.netbeans.modules.java.hints.spiimpl.RulesManagerImpl.readHints(RulesManagerImpl.java:139)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.computeHints(HintsInvoker.java:132)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsInvoker.computeHints(HintsInvoker.java:127)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsTask.run(HintsTask.java:113)
	at org.netbeans.modules.java.hints.spiimpl.hints.HintsTask.run(HintsTask.java:63)
[catch] at org.netbeans.modules.java.source.JavaSourceAccessor$CancelableTaskWrapper.run(JavaSourceAccessor.java:273)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callParserResultTask(TaskProcessor.java:561)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:786)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:279)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:702)
	at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:663)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
SEVERE [null]: Last record repeated again.
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Linux harmony 5.19.0-76051900-generic #202207312230~1660780566~22.04~9d60db1

### JDK

OpenJDK Runtime Environment 18.9 (build 11.0.2+9) OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

_No response_

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

### PR DESCRIPTION
**Pull request by errael**
This fixes #4651 in my case.

### CODE REVIEW

File: java/spi.java.hints/src/org/netbeans/modules/java/hints/spiimpl/Utilities.java [hunk 1]
```diff
@@ -1083,7 +1083,7 @@ public synchronized ClasspathInfo createUniversalCPInfo() {
             final JavaPlatformManager man = JavaPlatformManager.getDefault();
             if (select.getSpecification().getVersion() != null) {
                 for (JavaPlatform p : JavaPlatformManager.getDefault().getInstalledPlatforms()) {
-                    if (!"j2se".equals(p.getSpecification().getName()) || p.getSpecification().getVersion() == null) continue;
+                    if (!p.isValid() || !"j2se".equals(p.getSpecification().getName()) || p.getSpecification().getVersion() == null) continue;
                     if (p.getSpecification().getVersion().compareTo(select.getSpecification().getVersion()) > 0) {
                         select = p;
                     }
```
Comment (mbien) [inline java/spi.java.hints/src/org/netbeans/modules/java/hints/spiimpl/Utilities.java:1089]: the fix makes sense. But I believe this whole section needs some work. 

E.g if the default platform has no spec version, it would simply select the default platform without searching further?

how about:
```java
            final JavaPlatformManager man = JavaPlatformManager.getDefault();
            JavaPlatform select = Stream.concat(Stream.of(man.getInstalledPlatforms()), Stream.of(JavaPlatform.getDefault()))
                    .filter(JavaPlatform::isValid)
                    .filter((p) -> "j2se".equals(p.getSpecification().getName()))
                    .filter((p) -> p.getSpecification().getVersion() != null)
                    .max((p1, p2) -> p1.getSpecification().getVersion().compareTo(p2.getSpecification().getVersion()))
                    .orElse(JavaPlatform.getDefault());
```

Comment (errael) [reply java/spi.java.hints/src/org/netbeans/modules/java/hints/spiimpl/Utilities.java:1089]: > f the default platform has no spec version, it would simply select the default platform without searching further?

Yes, I see that; but is it wrong?

I'm not familiar with this code. Your suggestion makes sense in principle; but I don't know, and can't readily discern, if there might be some significance to a default platform with no spec.version. Clearly the original author made a decision about how to handle this. I'm uncomfortable changing the behavior of code paths I don't grok.

> not pick a version which goes beyond (nb-)javac

What would be the implication here if jdk-20 was picked and nb-javac only supported 19?

About the `Stream.concat`: isn't it required that the default platform be an installed platform?

---

Once I new how to fix the hints for my usage, it became a puzzle. I tried to see if I could find the **spot** without a lot of debugger action. I got lucky. I'm OK with closing this PR if you want to play with it, and would certainly watch for any discussion/changes. But I'm not qualified, without lots of effort, to go beyond avoiding a !valid platform

BTW, thanks for the `Stream` implementation. I've done little work with them. The more I work through some examples the better.

Comment (mbien) [reply java/spi.java.hints/src/org/netbeans/modules/java/hints/spiimpl/Utilities.java:1089]: > > f the default platform has no spec version, it would simply select the default platform without searching further?
> 
> Yes, I see that; but is it wrong?

my inspector gadget senses tell me that the loop appears to be there to select the most recent JDK. The null check might have been added to prevent a NPE in the loop, I can't imagine that it is supposed to ignore all configured platforms if the platform NB was started on doesn't have a spec version for whatever reason - but I might be wrong.

> >    not pick a version which goes beyond (nb-)javac

> What would be the implication here if jdk-20 was picked and nb-javac only supported 19?

Its an untested configuration and usually breaks things (netbeans expects having a javac of a certain version). NB also doesn't work very well if the runtime JDK is newer than nb-javac. In this case its better to uninstall nb-javac and hope for best. This situation would be similar. If nb-javac is uninstalled  and NB would be started on JDK 20, `SourceVersion.latest().ordinal()` would return 20 and it would be selected. With nb-javac, it would cap at 19 which is probably safer.

> Once I new how to fix the hints for my usage, it became a puzzle. I tried to see if I could find the spot without a lot of debugger action. I got lucky. I'm OK with closing this PR if you want to play with it, 

nono don't close - you did all the work. I can open a followup PR to add the upper bound check later.

> About the Stream.concat: isn't it required that the default platform be an installed platform?

the original code sets `JavaPlatform select = JavaPlatform.getDefault();` first. After that it checks if any of the `getInstalledPlatforms()` are better choices. The Stream picks the best installed platform first, and if there is none it falls back to default platform. Same result just other way around. Btw I might have edited the snipped while you replied - sorry for the confusion.

**Review by mbien — APPROVED** [review]
nice find!
