### PR TITLE
Fix possible CCE during auto completion of invalid code

### LINKED ISSUE #9172: ClassCastException in Java code completion
### Apache NetBeans version

Apache NetBeans 28

### What happened

The following ClassCastException repeatedly occurred during code completion in a file with syntax errors, intermittently breaking code completion:
```
java.lang.ClassCastException: class com.sun.tools.javac.code.Symbol$ClassSymbol cannot be cast to class javax.lang.model.element.ExecutableElement (com.sun.tools.javac.code.Symbol$ClassSymbol and javax.lang.model.element.ExecutableElement are in unnamed module of loader org.netbeans.StandardModule$OneModuleClassLoader @1426fa1e)
	at org.netbeans.modules.java.completion.JavaCompletionTask.getSmartTypesImpl(JavaCompletionTask.java:5999)
	at org.netbeans.modules.java.completion.JavaCompletionTask.getSmartTypes(JavaCompletionTask.java:5728)
	at org.netbeans.modules.java.completion.JavaCompletionTask.addMembers(JavaCompletionTask.java:4083)
	at org.netbeans.modules.java.completion.JavaCompletionTask.insideMemberSelect(JavaCompletionTask.java:1909)
	at org.netbeans.modules.java.completion.JavaCompletionTask.resolve(JavaCompletionTask.java:380)
	at org.netbeans.modules.java.completion.BaseTask.run(BaseTask.java:96)
	at org.netbeans.modules.java.completion.JavaCompletionTask.run(JavaCompletionTask.java:67)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callUserTask(TaskProcessor.java:586)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:197)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:180)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:181)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:178)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:178)
Caused: org.netbeans.modules.parsing.spi.ParseException
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:186)
	at org.netbeans.modules.parsing.api.ParserManager.parse(ParserManager.java:83)
[catch] at org.netbeans.modules.editor.java.JavaCompletionProvider$JavaCompletionQuery.query(JavaCompletionProvider.java:193)
	at org.netbeans.spi.editor.completion.support.AsyncCompletionTask.run(AsyncCompletionTask.java:198)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1403)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2018)
```

### Language / Project Type / NetBeans Component

_No response_

### How to reproduce

I can't provide the code where this happened (large file in a large proprietary code base), but the situation was that additional parameters were added to an existing method (temporarily breaking call sites for that method in the same source file), and the ClassCastException occurred while performing code completion within the argument list of one of the callers (while trying to add the new arguments for the new method parameters).

Similar to:
```java
void foo()
{
    bar(arg1, arg2, newArg2.<code completion here> );
}

void bar( A arg1, B arg2, C newArg3, D newArg4, E newArg5)
{
    ... also some syntax errors here ...
}

```

Closing the source file and reopening it, and first filling `null` for the multiple missing method arguments before re-attempting code completion, made code completion working again.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows

### JDK

JDK 21

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

While I can't provide a reproducible example, maybe the mismatched types causing the ClassCastException and the stacktrace are sufficient to track down where the bug is.

### Are you willing to submit a pull request?

No

### PR DESCRIPTION
**Pull request by mbien**
javac was observed to return `Elements` of types other than `ExecutableElement` for paths with `TypeMirror` kind `EXECUTABLE` in some cases.

adds an `instanceof` guard instead of assuming `ExecutableElement`

fixes #9172

### CODE REVIEW

File: java/java.completion/src/org/netbeans/modules/java/completion/JavaCompletionTask.java [hunk 1]
```diff
@@ -5996,7 +5996,7 @@ private Set<? extends TypeMirror> getSmartTypesImpl(Env env) throws IOException
                         path = new TreePath(path, mid);
                         TypeMirror typeMirror = controller.getTrees().getTypeMirror(path);
                         final ExecutableType midTM = typeMirror != null && typeMirror.getKind() == TypeKind.EXECUTABLE ? (ExecutableType) typeMirror : null;
-                        final ExecutableElement midEl = midTM == null ? null : (ExecutableElement) controller.getTrees().getElement(path);
+                        final ExecutableElement midEl = midTM != null && controller.getTrees().getElement(path) instanceof ExecutableElement ee ? ee : null;
```
Comment (mbien) [inline java/java.completion/src/org/netbeans/modules/java/completion/JavaCompletionTask.java:5999]: `midEl` and `midTM` are only used in 
https://github.com/apache/netbeans/blob/2fba977d4a4114ee346f34b0213a19948481a1dd/java/java.completion/src/org/netbeans/modules/java/completion/JavaCompletionTask.java#L6427

which is ok with any combination of null.

Comment (lahodaj) [reply java/java.completion/src/org/netbeans/modules/java/completion/JavaCompletionTask.java:5999]: Using `instanceof` on `Element`s is formally speaking not correct (`getKind()` should be used), as one implementation type can implement multiple API interfaces. Although I think use of `instanceof` will be accepted more and more. And it is not so bad for `Element`, as I don't recall implementation classes where this would be a real problem. (It is definitely a problem for certain `TypeMirror`s - the implementation type `ClassType` implements both `DeclaredType` and `ErrorType` API interfaces, and this effectively cannot be changed while keeping all other things working reasonably. There are also some rare `Tree`s where this is true.)

**Review by lahodaj — APPROVED** [review]
Looks OK.

File: java/java.completion/src/org/netbeans/modules/java/completion/JavaCompletionTask.java (hunk 1 above)
Comment (neilcsmith-net) [reply java/java.completion/src/org/netbeans/modules/java/completion/JavaCompletionTask.java:5999]: Wouldn't mind seeing an example of how this should be written like this.  I think I understand what you're getting at but it seems very similar to what was there already.

We don't have a utility that does this check somewhere?  Take TreePath, Kind and expected output Class?

Comment (mbien) [reply java/java.completion/src/org/netbeans/modules/java/completion/JavaCompletionTask.java:5999]: tbh 70% of the reason i wrote it that way is because the new `instanceof` get-check-and-assign pattern can be put into a one-liner which is the common style throughout the whole class. You could do something similar with `Optional` but it is less elegant IMO. (but of course this shouldn't be an excuse to write broken code ;))

I did have the `Kind` vs `implements` issue in the back of my head since @lahodaj explained it to me once, but I believe in this particular case it probably wouldn't matter the way the two variables are used. 

Having `TypeMirror` of kind `Executable` but the `Element` of a type other than `ExecutableElement` sounds to me like inconsistent state? I suppose thats why the original code casted it without kind check?

Comment (neilcsmith-net) [reply java/java.completion/src/org/netbeans/modules/java/completion/JavaCompletionTask.java:5999]: Yes, I assumed the point was that this should be checking the kind from the element being casted?  Although like you say the current situation seems inconsistent.  I've looked through a few reports and stack traces before we've had with CCE, and I just get the feeling it might be better to verify types as well as kind before casting.  I wondered if we had a utility somewhere already that does that.  Bonus if it also checks for `null` first.  Could simplify a few bits of this while keeping the logic in one place.

Comment (lahodaj) [reply java/java.completion/src/org/netbeans/modules/java/completion/JavaCompletionTask.java:5999]: I don't think we have a utility to fuse kind check and cast (although we could have - esp. for trees, as there's Kind.asInterface). Given we don't really support arbitrary Java Language Model (javax.lang.model), but only the one produced by javac, I think using instanceof for ExecutableElement is OKish.

FTR, the lines above show the kind check:
```
TypeMirror typeMirror = controller.getTrees().getTypeMirror(path);
final ExecutableType midTM = typeMirror != null && typeMirror.getKind() == TypeKind.EXECUTABLE ? (ExecutableType) typeMirror : null;
```
as Michael says, it is not easy to this without the auxiliary variable, esp. not without duplicating the `getTypeMirror` call. But, with source level >= 21, we could do:
```
final ExecutableElement midEl = midTM != null && controller.getTrees().getElement(path) instanceof Element ee && ee.getKind() == ElementKind.METHOD ? (ExecutableElement) ee : null;
```

As for the inconsistency, the attribution of erroneous code sometimes produces "funny" results - in particular, javac has no real `ExecutableElement` instance for really erroneous methods, its all either `ClassSymbol` or specialized subclases of `Symbol`, but not `MethodSymbol`/`ExecutableElement`, I think. I think I had some brief periods where I looked at possibilities to change this, but there I never found a viable solution.
