### PR TITLE
Small code cleanup in extbrowser module.

### LINKED ISSUE #6455: Links open in Edge instead of my default browser
### Apache NetBeans version

Apache NetBeans 19

### What happened

URLs open in Edge, not in my default browser (Vivaldi)

### How to reproduce

All URLs seem to be affected. The simplest way to reproduce is Help->Online Support

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 

### JDK

openjdk 19.0.2 2023-01-17 OpenJDK Runtime Environment (build 19.0.2+7-44) OpenJDK 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

I realize this may be very difficult due to Microsoft's continuing attempts to ignore my wishes on browser usage.  I will, however, note that Libre Office Writer opens its online help in my default browser.

### Are you willing to submit a pull request?

No

### PR DESCRIPTION
**Pull request by mbien**
I originally thought I could enable the `JdkBrowserImpl` by default due to #6455, but this could potentially cause feature regressions since the impl is fairly limited.

However, looking through the code I am wondering if any of the "DDE" features still work on windows for example.

Didn't want to discard the cleanup, so I opened this PR.

### CODE REVIEW

File: ide/extbrowser/src/org/netbeans/modules/extbrowser/NbDdeBrowserImpl.java [hunk 1]
```diff
@@ -413,7 +414,7 @@ private String getFileUrl(String url) {
             while ((f == null) && (retries > 0)) {
                 retries--;
                 try {
-                    f = File.createTempFile("extbrowser", ".html");             // NOI18N
+                    f = Files.createTempFile("extbrowser", ".html").toFile();             // NOI18N
```
Comment (mbien) [inline ide/extbrowser/src/org/netbeans/modules/extbrowser/NbDdeBrowserImpl.java:417]: this is usually more secure since it retains the file permissions of the process, however I just realized that this is windows so this doesn't matter...

**Review by matthiasblaesing — APPROVED** [review]
Looks sane to me.
