### PR TITLE
Fix NPE during project group creation caused by ergonomics

### LINKED ISSUE #6011: changing project group shows an exception in the log
### Apache NetBeans version

Apache NetBeans 18

### What happened

I changed the project group from one to another and this exception occurred:

```
java.lang.NullPointerException: Cannot invoke "java.util.Set.add(Object)" because "pwnr" is null
	at org.netbeans.modules.project.ui.ProjectUtilities$1.doClose(ProjectUtilities.java:155)
	at org.netbeans.modules.project.ui.ProjectUtilities$1.close(ProjectUtilities.java:116)
	at org.netbeans.modules.project.ui.ProjectUtilities.closeAllDocuments(ProjectUtilities.java:480)
	at org.netbeans.modules.project.ui.OpenProjectList.close(OpenProjectList.java:923)
	at org.netbeans.modules.project.ui.groups.Group.open(Group.java:586)
	at org.netbeans.modules.project.ui.groups.Group.setActiveGroup(Group.java:180)
	at org.netbeans.modules.project.ui.groups.ManageGroupsPanel$2$1.run(ManageGroupsPanel.java:80)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1419)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2034)
```

### How to reproduce

I don't know. After a restart of Netbeans I am able to switch project groups without this exception.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11

### JDK

JDK 17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

_No response_

### Are you willing to submit a pull request?

No

### PR DESCRIPTION
**Pull request by mbien**
Projects can change class type due to ergonomics. Hashcode/equals matching problems make storage in sets/maps problematic.

Unbox "FeatureNonProject" since https://github.com/apache/netbeans/blob/235b99afb8c555e26c460f31c9d65e0265eac892/ergonomics/ide.ergonomics/src/org/netbeans/modules/ide/ergonomics/fod/FeatureProjectFactory.java#L383-L393

isn't compatible with

https://github.com/apache/netbeans/blob/235b99afb8c555e26c460f31c9d65e0265eac892/java/maven/src/org/netbeans/modules/maven/NbMavenProjectImpl.java#L1336-L1355

discovered while implementing https://github.com/apache/netbeans/pull/8164

fixes #6011, https://issues.apache.org/jira/browse/NETBEANS-2167 and https://bz.apache.org/netbeans/show_bug.cgi?id=235897

reproducer:
 1) clean NB config, don't import on start
 2) open existing maven project
 3) open any project file
 4) create new project group -> NPE

### CODE REVIEW

**Comment by mbien** [comment]
something isn't working correctly. tabs close now when a pg is created for a project loaded by ergonomics. i swear this worked when i tested it :(

File: ide/projectui/src/org/netbeans/modules/project/ui/OpenProjectList.java [hunk 1]
```diff
@@ -1379,6 +1376,7 @@ private boolean doOpenProject(final @NonNull Project p) {
             public @Override Boolean run() {
             log(Level.FINER, "already opened: {0} ", openProjects);
             for (Project existing : openProjects) {
+                // TODO double tap ???
                 if (p.equals(existing) || existing.equals(p)) {
```
Comment (mbien) [inline ide/projectui/src/org/netbeans/modules/project/ui/OpenProjectList.java:1380]: this is either a harmless mistake or a red flag

File: ide/projectui/src/org/netbeans/modules/project/ui/groups/Group.java [hunk 2]
```diff
@@ -562,7 +562,15 @@ static void open(final Group g, String oldGroupName, boolean isNewGroup, Prefere
...
-            Set<Project> oldOpen = new HashSet<Project>(Arrays.asList(opl.getOpenProjects()));
+            
+            Set<Project> oldOpen = new HashSet<>();
+            for (Project open : Arrays.asList(opl.getOpenProjects())) {
+                // TODO fix this properly
+                // unbox potential fod.FeatureNonProject wrapper since it breaks Sets/Maps due to incompatible hashcode impls
+                Project real = open.getLookup().lookup(Project.class);
+                oldOpen.add(real != null ? real : open);
+            }
+
```
Comment (mbien) [inline ide/projectui/src/org/netbeans/modules/project/ui/groups/Group.java:573]: this is the workaround

File: ide/projectui/src/org/netbeans/modules/project/ui/OpenProjectList.java (hunk 1 above)
Comment (eirikbakke) [reply ide/projectui/src/org/netbeans/modules/project/ui/OpenProjectList.java:1380]: I often turn to @emilianbold's helpful [git dump](https://github.com/emilianbold/netbeans-releases) of the old NetBeans Mercurial logs for curiosities like these. Here's the relevant commit:

https://github.com/emilianbold/netbeans-releases/commit/56b427cd661de066f5e5ec644099f74a37000605

There's a Bugzilla issue number 156536 referenced, but the [archive](https://bz.apache.org/netbeans/describecomponents.cgi) doesn't seem to work anymore.

Comment (mbien) [reply ide/projectui/src/org/netbeans/modules/project/ui/OpenProjectList.java:1380]: ok. so its a red flag of a broken equals contract too. Not only hash code.

File: ide/projectui/src/org/netbeans/modules/project/ui/groups/Group.java (hunk 2 above)
Comment (eirikbakke) [reply ide/projectui/src/org/netbeans/modules/project/ui/groups/Group.java:573]: The TODO comment would be improved by suggesting what the proper fix might look like.

What exactly is a FeatureNonProject? I found the class but it's light on comments. Some placeholder object for projects that are not fully loaded yet?

File: ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java [hunk 3]
```diff
@@ -135,28 +130,25 @@ private void doClose(Project[] projects, boolean notifyUI, Wrapper wr) {
...
-                        assert pf != null;
-                        URL u = pf.toURL();
-                        assert u != null;
-                        String uex = u.toExternalForm();                        
-                        pwnr.add(uex);
+                        Set<String> files = project2FilesMap.get(owner);
+                        if (files != null) {
+                            files.add(fobj.toURL().toExternalForm());
+                        } else {
+                            LOG.log(Level.WARNING, "project accociation lost, project ({1}) might lose an opened file ({2}) on reopen", new Object[] {owner, fobj});
```
Comment (eirikbakke) [inline ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java:147]: typo: association

File: ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java [hunk 4]
```diff
@@ -135,28 +130,25 @@ private void doClose(Project[] projects, boolean notifyUI, Wrapper wr) {
...
-                    if (listOfProjects.contains(owner)) {
+                    if (owner != null && listOfProjects.contains(owner)) {
                         if (notifyUI) {
                             openFiles.add(dobj);
                             tc2close.add(tc);
                         } else if (!dobj.isModified()) {
                             // when not called from UI, only include TCs that arenot modified
                             tc2close.add(tc);
                         }
-                        //#235897 split a single line to detect NPE better
```
Comment (eirikbakke) [inline ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java:148]: I guess you may have found the NPE they were search for 12 years ago in https://bz.apache.org/netbeans/show_bug.cgi?id=235897 ...

File: ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java (hunk 3 above)
Comment (eirikbakke) [inline ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java:147]: How can this case happen? If files == null it means owner was never added to project2FilesMap. But all projects in listOfProjects were added to project2FilesMap before, and we are currently in an if condition that runs only if listOfProjects.contains(owner).

File: ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java [hunk 5]
```diff
@@ -135,28 +130,25 @@ private void doClose(Project[] projects, boolean notifyUI, Wrapper wr) {
                 if (dobj != null) {
                     FileObject fobj = dobj.getPrimaryFile();
                     Project owner = ProjectConvertors.getNonConvertorOwner(fobj);
-                    ERR.log(Level.FINER, "Found {0} owned by {1} in {2} of {3}", new Object[] {fobj, owner, tc.getName(), tc.getClass()});
+                    LOG.log(Level.FINER, "Found {0} owned by {1} in {2} of {3}", new Object[] {fobj, owner, tc.getName(), tc.getClass()});
 
-                    if (listOfProjects.contains(owner)) {
```
Comment (eirikbakke) [inline ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java:140]: It would be cleaner to just get `Set<String> files = project2FilesMap.get(owner);` here and change the test to `files != null`. Then change the earlier loop to just `for (Project p : projects)` and get rid of listOfProjects altogether.

File: ide/projectui/src/org/netbeans/modules/project/ui/groups/Group.java (hunk 2 above)
Comment (mbien) [reply ide/projectui/src/org/netbeans/modules/project/ui/groups/Group.java:573]: it appears to be a placeholder which is used by the ergonomics mechanism to represent project functionality before the cluster for the functionality is loaded. At this point, the cluster is already loaded, but code has still the activation proxy stored.

File: ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java (hunk 3 above)
Comment (mbien) [reply ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java:147]: broken equals/hashcode contracts.

After the added workaround which unboxes the project this shouldn't happen anymore. This is just a safety measure which prints something instead of throwing NPEs in case some edge case got overlooked.

File: ide/projectui/src/org/netbeans/modules/project/ui/groups/Group.java (hunk 2 above)
Comment (mbien) [reply ide/projectui/src/org/netbeans/modules/project/ui/groups/Group.java:573]: > The TODO comment would be improved by suggesting what the proper fix might look like.

IMO: the proper fix would be to repair equals/hashcode. Once done `opl.getOpenProjects()` should be changed to return only unboxed projects - since I don't think projects can be open without their cluster loaded.

However: realistically, I am not sure if this can be done at this point since it is quite risky. The getter is exposed via public API and fixing object identity mechanics could break other things, given how many workaround already exist (e.g the `a.equals(b) || b.equals(a)` situation). If at all this must be done carefully and might need some refactoring first before attempting it.

File: ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java (hunk 4 above)
Comment (mbien) [reply ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java:148]: yep I hope so. Although it might be still more to it.

File: ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java (hunk 3 above)
Comment (mbien) [reply ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java:147]: concrete example: the list of open projects might contain the `FeatureNonProject` wrapper, `owner` however is the real project -> contains/remove etc won't work and the code breaks

File: ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java (hunk 5 above)
Comment (mbien) [reply ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java:140]: good idea - will give it a try!

Comment (mbien) [reply ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java:140]: done

File: ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java (hunk 4 above)
Comment (eirikbakke) [reply ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java:148]: > the extra steps to locate NPEs are also no longer needed thanks to https://openjdk.org/jeps/358
Yep.

File: ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java [hunk 6]
```diff
@@ -135,28 +130,23 @@ private void doClose(Project[] projects, boolean notifyUI, Wrapper wr) {
...
-                        assert pwnr != null : "Owner project for file:" + fobj + " prj:" + owner;
-                        final FileObject pf = fobj;
-                        assert pf != null;
-                        URL u = pf.toURL();
-                        assert u != null;
-                        String uex = u.toExternalForm();                        
-                        pwnr.add(uex);
+                        files.add(fobj.toURL().toExternalForm());
+                    } else {
+                        LOG.log(Level.WARNING, "project association lost, project ({1}) might lose an opened file ({2}) on reopen", new Object[] {owner, fobj});
```
Comment (eirikbakke) [inline ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java:146]: Sorry, one more case to ask about...

What about files that are not associated with a project? E.g. if you open a file not in a project with "Open File" in the "File" menu. Does ProjectConvertors.getNonConvertorOwner(fobj) return null in that case? The loop should probably quietly skip such files without closing them or logging a warning.

(Sorry I didn't see this earlier...)

File: ide/projectui/src/org/netbeans/modules/project/ui/OpenProjectList.java [hunk 7]
```diff
@@ -1379,6 +1376,7 @@ private boolean doOpenProject(final @NonNull Project p) {
             public @Override Boolean run() {
             log(Level.FINER, "already opened: {0} ", openProjects);
             for (Project existing : openProjects) {
+                // TODO double tap ???
```
Comment (eirikbakke) [inline ide/projectui/src/org/netbeans/modules/project/ui/OpenProjectList.java:1379]: Proposed improved comment:
`// An old hack due to broken equals() contract; see https://bz.apache.org/netbeans/show_bug.cgi?id=156536`

File: ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java (hunk 6 above)
Comment (mbien) [reply ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java:146]: good point. will only log the warning if owner != null

Comment (mbien) [reply ide/projectui/src/org/netbeans/modules/project/ui/ProjectUtilities.java]: updated

> (Sorry I didn't see this earlier...)

no worries - I am very iterative myself - keep the comments coming :)

**Review by eirikbakke — APPROVED** [review]
Looks good, thank you! (Would be good to do just a final manual test with the latest version of the code before merging.)

**Comment by mbien** [comment]
planning to merge this today
