### PR TITLE
Try to close Gradle Daemons on exit.

### LINKED ISSUE #6303: Gradle daemon is left opened after NetBeans IDE is closed
### Apache NetBeans version

Apache NetBeans 18

### What happened

Unlikely to other IDEs like IntelliJ IDEA or Eclipse, NetBeans IDE doesn't terminate Gradle Daemon after IDE is closed.

I've checked if the Gradle Daemon is created from NetBeans or not with System Informer.

<details><summary>Click to expand detailed information with screenshot</summary>

  
`netbeans64.exe`(PID 10588) created `java.exe`(PID 2072) as its 'child process / subprocess'(I don't know how to call this correctly). As you can see, the `java.exe` is Gradle Daemon.

Now I close NetBeans IDE.  
  
`java.exe`(PID 2072) is now orphaned. You can distinguish this `java.exe` is the same `java.exe` at the first screenshot by its PID and command argument.

</details>

Maybe this is intended behavior. But I think if it is intended, NetBeans should provide option for disable that behavior.

I tried other IDEs like IntelliJ IDEA or Eclipse, and they properly terminated Gradle Daemon after closing them.

### How to reproduce

0. Check if there is any `java.exe` is running & close it  
   This is not that important, but I'm doing this to make sure that the orphaned `java.exe` is created by NetBeans IDE.
1. Open NetBeans IDE 18  
   I enabled following plugins to use Gradle with NetBeans IDE
   * Gradle Editor Support
   * DuckScript Gradle Project Wizard
   * Gradle Projects Distributions
   * Gradle
   * Gradle Projects
   * Groovy
2. Run Gradle task at least once  
   In my configuration, Gradle Daemon is not started automatically. So, to initialize Gradle Daemon, I have to run Gradle task to initialize it.
3. Check if any Gradle task is running  
   Do not close IDE while Gradle task is running. I think IDE would show warning about that if Gradle task is still running anyway.
4. Close IDE  
5. Check if Gradle Daemon(`java.exe`) is still running

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11 22H2 (OS build: 22621.2070)

### JDK

openjdk 17.0.7 2023-04-18  
OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)  
OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)

### Apache NetBeans packaging

Apache NetBeans provided installer, Apache NetBeans binary zip

### Anything else

I'm not sure if this is related to other issue which NetBeans IDE cannot load Gradle task properly, making external dependencies as 'missing dependencies' even though it is specified at `build.gradle`. See https://github.com/apache/netbeans/issues/4779.

Maybe https://github.com/apache/netbeans/issues/4419 would be related to this. But the issue is closed and a year ago, I think I should just open a new issue about this.

Path of `%GRADLE_USER_HOME%` is manually set to change where Gradle stuff are saved. There is no issue about path of Gradle stuff.

### Are you willing to submit a pull request?

No

### PR DESCRIPTION
**Pull request by lkishalmi**
It seems `GradleConnector` has a `disconnect()` method since 6.5. Calling that should stop daemons started by these connectors.

This one tries to fix #6303, by centralizing the previously freely created `GradleConnector`s.

### CODE REVIEW

File: extide/gradle/src/org/netbeans/modules/gradle/GradleConnectorManager.java [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+    
+    private final Map<Project, GradleConnector> projectConnector = new WeakHashMap<>();
+    private final List<GradleConnector> connectors = new ArrayList<>();
+
+    private static final GradleConnectorManager INSTANCE = new GradleConnectorManager();
+    private static final Logger LOG = Logger.getLogger(GradleConnectorManager.class.getName());
+    
+    public static GradleConnectorManager getDefault() {
+        return INSTANCE;
+    }
```
Comment (mbien) [inline extide/gradle/src/org/netbeans/modules/gradle/GradleConnectorManager.java:44]: consider to guard with private constructor:
```
    private GradleConnectorManager() {}
```

**Review by mbien — APPROVED** [review]
looks good!

questions:
what happens if a project changes settings, like the gradle version, would this require a fresh connector or will the old one from the map still work?

can a project disconnect itself if it is closed? Wondering if there is an event for that.

File: extide/gradle/src/org/netbeans/modules/gradle/GradleConnectorManager.java [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+            });
+            return ret;            
+        }
+    }
+    
+    
+    public void disconnectAll() {
+        LOG.info("Disconnecting from Gradle Daemons."); //NOI18N
+        synchronized (connectors) {
+            connectors.iterator().forEachRemaining(GradleConnector::disconnect);
```
Comment (mbien) [inline extide/gradle/src/org/netbeans/modules/gradle/GradleConnectorManager.java:61]: `connectors.forEach(GradleConnector::disconnect);` ?

Comment (lkishalmi) [reply extide/gradle/src/org/netbeans/modules/gradle/GradleConnectorManager.java:64]: Well, it could be `forEach()` then a `clean()`. The plan is to have this method callable when needed, so it can free up resources, for example when the GRADLE_USER_HOME is changed in the IDE or for testing purposes. Not figured out the real need of the `disconnectAll()` invocations other than the IDE shutdown.

I think `GradleConnector` is a badly placed entrypoint to the Tooling API a strange mixture of a builder, some connection accounting, etc. 

Theoretically one instance of GradleConnector could be enough, though it is not thread safe and it's `useXXX`, `forXXX` methods are changing the state of an internal builder. That would require some kind of locking/synchronization. I hope I'd be wiser over time to deal with this better.

**Comment by lkishalmi** [comment]
> looks good!
> 
> questions: what happens if a project changes settings, like the gradle version, would this require a fresh connector or will the old one from the map still work?

Yes, theoretically even one connector would be enough.

> 
> can a project disconnect itself if it is closed? Wondering if there is an event for that.
That's a good question. The answer is yes and no, as the actual `disconnect()` method is implemented on the `DefaultProjectConnection` (Gradle internal), however that method is not exported through the `ProjectConnection` interface, also calling the `close()` method would not call it implicitly.

File: extide/gradle/src/org/netbeans/modules/gradle/GradleConnectorManager.java (hunk 2 above)
Comment (mbien) [reply extide/gradle/src/org/netbeans/modules/gradle/GradleConnectorManager.java:64]: not sure I understand. `forEachRemaining` isn't removing anything from the iterator.

You create a list iterator and iterate through it. This can be shortened into list.forEach(), both should be equivalent.

You can still clear the list afterwards of course.

Comment (lkishalmi) [reply extide/gradle/src/org/netbeans/modules/gradle/GradleConnectorManager.java]: Wow! You are right! Probably I should not read JavaDoc after 4 hours sleep. I was so happy, that I found something new for draining a collection. It seems I've just mixed the `remove` and `forEachRemaining` while read that in the morning.

Thanks for putting me back to the track!

Comment (mbien) [reply extide/gradle/src/org/netbeans/modules/gradle/GradleConnectorManager.java]: no problem at all! this is a fairly exotic method tbh. I believe the reason why it is named that way is because a iterator can be at an arbitrary position, so forEach could be misleading if it is not a fresh iterator. Also get some sleep 4h is not enough :(
