### PR TITLE
DiffView: delegate mouse scroll events from lines bar to editor.

### LINKED ISSUE #6995: Diff window scroll bug
### Apache NetBeans version

Apache NetBeans 20

### What happened

When I place the mouse on any of the line number columns in the Diff window and swipe two fingers up/down to scroll the lines, only the line number part scrolls, not the lines themselves.

I can reproduce this with NB20 & NB21-rc1 on different linux systems with X and Wayland,
on windows it works as expected.

Screenshot with scrolled numbers in a file without major changes..

bild

### Language / Project Type / NetBeans Component

_No response_

### How to reproduce

Place the mouse on any of the line number columns in the Diff window and swipe two fingers up/down to scroll the lines.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Linux

### JDK

21.0.1; OpenJDK 64-Bit Server VM 21.0.1+12-LTS; Azul Systems, Inc.

### Apache NetBeans packaging

Apache NetBeans Snap Package

### Anything else

_No response_

### Are you willing to submit a pull request?

No

### PR DESCRIPTION
**Pull request by mbien**
The `LineNumbersActionsBar` got a mind of its own and started scrolling on JDK 19+ on mouse wheel events without the rest of the diff view.

This simply delegates the events to the attached editor component, so that everything can scroll together.

fixes #6995

### CODE REVIEW

File: ide/diff/src/org/netbeans/modules/diff/builtin/visualizer/editable/DiffContentPanel.java [hunk 1]
```diff
@@ -67,6 +67,8 @@ public DiffContentPanel(EditableDiffView master, boolean isFirst) {
         add(scrollPane);
         
         linesActions = new LineNumbersActionsBar(this, master.isActionsEnabled());
+        linesActions.addMouseWheelListener(e -> editorPane.dispatchEvent(e)); // delegate mouse scroll events to editor
+
```
Comment (mbien) [inline ide/diff/src/org/netbeans/modules/diff/builtin/visualizer/editable/DiffContentPanel.java:71]: should we do this instead?
```java
        linesActions.addMouseWheelListener(e -> {
            editorPane.dispatchEvent(e); // delegate mouse scroll events to editor
            e.consume();
        });
```
i am slightly worried that this is a JDK bug, since this did already stop the scrolling:
```java
        linesActions.addMouseWheelListener(e -> {});
```

**Comment by mbien** [comment]
> Are the line numbers and text editor in two separate JScrollPane parents that are normally synced together somehow?

right, otherwise the line numbers would scroll horizontally with the editor. They have their own scroll pane which scrolls only vertically and is linked to the editor they belong to. Then the two editors are linked in the diff view to one scroll bar, but mouse wheel allows to scroll them individually.

> If there's a JDK bug, what is the expected vs. actual behavior of the JScrollPane?

for once the behavior should not change just by adding an empty mouse wheel listener. Which is why I thought about calling consume() after redispatch.

**Comment by neilcsmith-net** [comment]
Suspect caused by this change - https://bugs.openjdk.org/browse/JDK-6911375 / https://github.com/openjdk/jdk19u/commit/832729b41e690d6f05da71997bbe2a74b2d6dada ??

File: ide/diff/src/org/netbeans/modules/diff/builtin/visualizer/editable/DiffContentPanel.java (hunk 1 above)
Comment (eirikbakke) [reply ide/diff/src/org/netbeans/modules/diff/builtin/visualizer/editable/DiffContentPanel.java:71]: Either is fine with me, as long as it works on all platforms.

**Review by eirikbakke — APPROVED** [review]
I'm fine with whichever solution seems to work here. Ideally we'd test this it on all three platforms (Windows, Linux, and MacOS), though. I'm on Windows myself and can test there.

File: ide/diff/src/org/netbeans/modules/diff/builtin/visualizer/editable/DiffContentPanel.java (hunk 1 above)
Comment (mbien) [reply ide/diff/src/org/netbeans/modules/diff/builtin/visualizer/editable/DiffContentPanel.java:71]: I tested it on linux

**Comment by neilcsmith-net** [comment]
The bug and fix I linked to in JDK 19 makes the scroll pane react to mouse wheel events even when no scroll bar is visible.  Our code seems to rely on them never being there to filter out scrolling.

> Fact is that adding an empty mouse wheel listener, already restores the old behavior on JDK 19+: nothing happens on scroll over the line number bar. I can't remember of an instance that adding an empty listener did ever change behavior in swing before!

It's not that unusual that adding a listener filters events being handed up to the ancestor.  See the documentation for `MouseWheelEvent` -

```
 * MouseWheelEvents start delivery from the Component underneath the
 * mouse cursor.  If MouseWheelEvents are not enabled on the
 * Component, the event is delivered to the first ancestor
 * Container with MouseWheelEvents enabled.  This will usually be
 * a ScrollPane with wheel scrolling enabled.
```

The fix seems to make sense to me.  And also that there is not a JDK bug involved.

**Comment by mbien** [comment]
>  Our code seems to rely on them never being there to filter out scrolling.

filtering out scrolling already is a bug since the regular editor behaves differently. This likely is just a coincidence, nobody wanted to actually ignore events there. Users only noticed when the numbers bar started to move that everything should have moved from the first place.

**Comment by neilcsmith-net** [comment]
Users noticed the numbers bar moving because the JDK bug is now fixed, so I assume filtering was desired unless the current behaviour should be considered correct! :wink:

Anyway, the fix looks right for now.  Ideally I guess it would be using https://docs.oracle.com/en/java/javase/17/docs/api/java.desktop/javax/swing/JScrollPane.html#setRowHeaderView(java.awt.Component) rather then two scroll panes?

**Comment by mbien** [comment]
> so I assume filtering was desired unless the current behaviour should be considered correct!

that is in fact the question. This PR assumes the behavior of the regular editor is correct, and that the diff view never was correct, the moving numbers bar only made the problem clearly visible.

If you want the JDK 11 behavior I can remove the event redispatch.

**Comment by neilcsmith-net** [comment]
I think we're meaning slightly different things by filtering there.  Yes, keep the event dispatch.  Closer to main editor UI the better IMO.
