### PR TITLE
use java.home as "default jdk" if jdk.home leads to symlinks.

### LINKED ISSUE #4365: java.lang.NullPointerException when creating new JFrame Form
### Apache NetBeans version

Apache NetBeans 14

### What happened

Create a new Java project then a new JFrame Form. Expected to see elements on palette but only Beans is shown and an exception appears in notification panel.
Same happens every time I open that JFram Form

### How to reproduce

Create a new JFrame Form

### Did this work correctly in an earlier version?

No

### Operating System

Ubuntu 22.04 LTS

### JDK

openjdk version "11.0.15" 2022-04-19 OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.22.04.1) OpenJDK 64-Bit Server VM (build 11.0.15+10-Ubuntu-0ubuntu0.22.04.1, mixed mode, sharing)

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

```
java.lang.NullPointerException
	at org.netbeans.modules.form.project.ClassSource.addToProjectClassPath(ClassSource.java:89)
	at org.netbeans.modules.form.project.ClassPathUtils$1.run(ClassPathUtils.java:233)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

image
image

Something similar happens when I try with Netbeans 12

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

### PR DESCRIPTION
**Pull request by mbien**
- /usr shouldn't be a valid path for the default JDK
   - use java.home if jdk.home/bin/java is a symlink
   - updated some related warning messages
   - fixes #4365

NB can't actually be started on a "JRE" (whatever a JRE is these days since it isn't well defined anymore). However, the "default jdk" path could be invalid still which will cause trouble at runtime. (looking at you, installer)

e.g trying to run NB on a "JRE" fails early so we don't have to worry about this scenario (at least not for the IDE):
```
./netbeans 
Error occurred during initialization of boot layer
java.lang.module.FindException: Module jdk.jshell not found
```

### CODE REVIEW

File: java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/DefaultPlatformImpl.java [hunk 1]
```diff
@@ -42,8 +48,15 @@ public class DefaultPlatformImpl extends J2SEPlatformImpl {
...
 
-    private ClassPath standardLibs;
+    @StaticResource
+    private static final String WARNING_ICON = "org/netbeans/modules/java/j2seplatform/resources/warning.png"; //NOI18N
 
+    @NbBundle.Messages({
+        "TITLE_InvalidDefaultJDK=Invalid JDK Home detected",
+        "DESC_InvalidDefaultJDK=The jdk.home property does not set a path to a valid JDK." +
+                               "Please update netbeans_jdkhome in your netbeans.conf" +
+                               "or start netbeans with --jdkhome /path/to/JDK set."
```
Comment (mbien) [inline java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/DefaultPlatformImpl.java:58]: how comes that `NotificationDisplayer` doesn't support html or `\n` line breaks? This creates a fairly long line.

File: java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/DefaultPlatformImpl.java [hunk 2]
```diff
@@ -84,6 +102,12 @@ static JavaPlatform create(Map<String,String> properties, List<URL> sources, Lis
         return new DefaultPlatformImpl(installFolders, properties, systemProperties, sources, javadoc);
     }
 
+    private static boolean isValidJDKHome(Path javaHome) {
+        return Files.exists(javaHome.resolve(Path.of("bin", "java")))
+            && Files.exists(javaHome.resolve(Path.of("bin", "javac")));
+//            && Files.exists(javaHome.resolve(Path.of("jmods", "java.base.mod")));   // TODO: uncomment once everything migrated to 11+
```
Comment (neilcsmith-net) [inline java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/DefaultPlatformImpl.java:108]: Did you test this? Because that's probably still returning `true`.  The IDE wouldn't launch otherwise.  The problem is that those files are symlinks.  Are there any circumstances that `java.home` will not be correct?  I would either default to that, or at least default to that if `<jdk.home>/bin/java` is a symlink.

**Review by neilcsmith-net — CHANGES_REQUESTED** [review]

File: java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/DefaultPlatformImpl.java (hunk 1 above)
Comment (neilcsmith-net) [reply java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/DefaultPlatformImpl.java:58]: I assume you tested the message starting with `<html>`?

File: java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/DefaultPlatformImpl.java (hunk 2 above)
Comment (mbien) [reply java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/DefaultPlatformImpl.java:108]: I tested this with the jmods line uncommented, but then I realized that this is probably used by VSCode too.

So you are saying the `jdk.home` property has no use at this point in the lifecycle anymore, I should simply change it to `java.home`, do no validation and therefore also no notifications since it can't ever be wrong at this point?

File: java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/DefaultPlatformImpl.java (hunk 1 above)
Comment (mbien) [reply java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/DefaultPlatformImpl.java:58]: it simply rendered with the html tags in plain text. but Disregard this, we probably don't need a notification.

File: java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/DefaultPlatformImpl.java (hunk 2 above)
Comment (neilcsmith-net) [reply java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/DefaultPlatformImpl.java:108]: Well, I was going to put in a PR along the lines of the second option. Think that's probably safer? Using `jdk.home` was presumably added for some reason.

File: java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/DefaultPlatformImpl.java (hunk 1 above)
Comment (neilcsmith-net) [reply java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/DefaultPlatformImpl.java:58]: Yes, disregard for this. Although I thought there was code in there to special case html. Will take a look sometime.

File: java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/DefaultPlatformImpl.java (hunk 2 above)
Comment (mbien) [reply java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/DefaultPlatformImpl.java]: ok changed, this makes things easier. Although having jdk.home set to /usr seems to be a fairly specific misconfiguration scenario. I am sure there are more creative ways how to have an invalid jdk.home set? I guess we will see in future :)

**Comment by mbien** [comment]
tested the following:
1) set netbeans_jdkhome to `/usr`
2) started NB and made sure platform had been changed to `/usr/lib/jvm/java-18-openjdk`

**Review by neilcsmith-net — APPROVED** [review]
Haven't tested yet, but looks good.

I think there are only a select few cases where the jdkhome setting will get through launching the iDE but the platform be broken. In the installer, this looks like it's probably the problem in this case. https://github.com/apache/netbeans/blob/master/nbi/engine/src/org/netbeans/installer/wizard/components/actions/SearchForJavaAction.java#L515 Mind you, I'd prefer the installer didn't try and set this at all.

File: java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/DefaultPlatformImpl.java (hunk 2 above)
Comment (mbien) [reply java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/DefaultPlatformImpl.java]: @neilcsmith-net I should have let you do the PR. It probably took you as much time answering my questions as if you would have done it right away. Its just that I had it already started together with the NPE PR and split it later.
