### PR TITLE
Fix Project Group window EDT race condition and update UX

### LINKED ISSUE #6768: New Project Group dialog not being brought to front
### Apache NetBeans version

Apache NetBeans 20 release candidate

### What happened

Small GUI-related issue; probably a simple fix. Couldn't find it already listed as bug, so decided to file.

Trying to create a new **Project Group** from **Manage Groups** dialog leaves the new group dialog in the background, so need to deselect/reselect application to bring it to focus (or similar needless shenanigans).

### How to reproduce

_File_ / _Project Groups..._ / _New Group..._

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

macOS Sonoma 14.1.1 (Apple Silicon)

### JDK

Adoptium OpenJDK 21

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

_No response_

### Are you willing to submit a pull request?

No

### PR DESCRIPTION
**Pull request by mbien**
The modal project-group dialog can open a modal create-group dialog as last action before it disposes. This apparently creates a race condition since the create-group dialog can receive a parent which just disappeared - leading to weird UI behavior as soon someone tries to click on the main window.

`SwingUtilities.invokeLater` seems to be sufficient to make sure the first dialog is gone before the second opens so that it can get a proper parent, which is usually the main window.

 - second commit fixes https://issues.apache.org/jira/browse/NETBEANS-6143
 - third commit makes sure the new-group dialog opens manage-group again to have a logical flow
    `main window` -> `manage groups` -> `create groups` -> `manage groups `-> `main window`

rest is code cleanup

fixes #6768 and [NETBEANS-6143](https://issues.apache.org/jira/browse/NETBEANS-6143)

### CODE REVIEW

File: ide/projectui/src/org/netbeans/modules/project/ui/groups/GroupsMenu.java [hunk 1]
```diff
@@ -137,36 +129,20 @@ private static void manageGroups() {
...
-        newGroup.addActionListener(new ActionListener() {
-
-            @Override
-            public void actionPerformed(ActionEvent e) {
-                newGroup();
-            }
-        });
+        // invokeLater ensures that the parent is disposed before the new dialog opens
+        // so that it can set a parent which doesn't disappear - fixes race condition
+        newGroup.addActionListener(e -> SwingUtilities.invokeLater(GroupsMenu::newGroup));
```
Comment (mbien) [inline ide/projectui/src/org/netbeans/modules/project/ui/groups/GroupsMenu.java:145]: thats the fix, rest is cleanup.

The UX is a bit weird here since creating a group closes both dialogs - what if a user wants to create a group and then switch to another group? Or create two groups?
Not closing the first dialog would require a few more updates, e.g. the list doesn't update, and UX-wise it would also be not ideal to create a group and having to press cancel to get out of the dialog (select group reloads the group).

Comment (mbien) [reply ide/projectui/src/org/netbeans/modules/project/ui/groups/GroupsMenu.java]: ^ third commit changes this so that the new-group dialog opens manage-groups again

**Review by neilcsmith-net — APPROVED** [review]
Makes sense!  Not tested.

I've quite often had issues in platform apps before moving dialog code into invoke later.
