### PR TITLE
Handle jakarta package in bean validation constraint template

### LINKED ISSUE #5592: javax imports in a JakartaEE 10 Web Project - Validation Constraint.
### Apache NetBeans version

Apache NetBeans 17

### What happened

Creating a new validation constraint (Bean Validation Section) through the UI Wizard still generates imports related to JavaEE even when the project is using JakartaEE 10.

```Java
import javax.validation.Constraint;
import javax.validation.Payload;
```

Instead of

```Java
import jakarta.validation.Constraint;
import jakarta.validation.Payload;
```

Now. I am not sure if this is actually a bug or even an issue, because some folks may still be using NetBeans to develop JavaEE Applications.

### How to reproduce

**Steps to reproduce it.**

- Right click over your project.
- Select "New"
- Select "Other" from the contextual submenu.
- Select "Bean Validation" in the presented dialog box.
- Choose "Validation Constraint" in the "File Types" section located to the right.
- Click "Next" button.

Fulfill the required information. e.g.
 NewValidationConstraintWizardNetBeans17

- Click "Finish" button.

You will see the aforementioned imports.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11, NetBeans 17 is being run over WSL2 (Ubuntu 22.04.2 LTS)

### JDK

java version "17.0.5" 2022-10-18 LTS Java(TM) SE Runtime Environment (build 17.0.5+9-LTS-191) Java HotSpot(TM) 64-Bit Server VM (build 17.0.5+9-LTS-191, mixed mode, sharing)

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

Every time.

### Are you willing to submit a pull request?

Yes

### PR DESCRIPTION
**Pull request by NicolaIsotta**
fixes #5592 

Tested in EE and non EE projects

This also let the user edit the ConstraintValidator template, it was unaccessible before.

### CODE REVIEW

File: enterprise/javaee.beanvalidation/src/org/netbeans/modules/javaee/beanvalidation/ConstraintIterator.java [hunk 1]
```diff
@@ -196,24 +203,48 @@ public void addChangeListener(ChangeListener l) {
...
+    
+    private static boolean isJakartaPackage(Project project) {
+        Profile profile = JavaEEProjectSettings.getProfile(project);
+        if (profile != null) {
+            return profile.isAtLeast(Profile.JAKARTA_EE_9_WEB);
+        }
+
+        Sources sources = ProjectUtils.getSources(project);
+        if (sources == null) {
+            return false;
```
Comment (matthiasblaesing) [inline enterprise/javaee.beanvalidation/src/org/netbeans/modules/javaee/beanvalidation/ConstraintIterator.java]: I would default to Jakarta if we can't get evidence, that  the javax namespace is used.

**Comment by matthiasblaesing** [comment]
Thank you!
