### PR TITLE
Stack trace parser fixes

### LINKED ISSUE #7385: Link to test source doesn't work
### Apache NetBeans version

Apache NetBeans 22 release candidate

### What happened

NB doesn't open link to test file and test method.

### Language / Project Type / NetBeans Component

Java Maven Project using Java Modules (JPMS)

### How to reproduce

This is a test project - https://github.com/PavelTurk/nb-test-link. The project contains one broken test. If you try to build in in NB you will get:

Screenshot from 2024-05-20 13-03-23

The problem is that when you click the link to test source (link is selected in the picture) then nothing happens - NB doesn't open that test file in test method.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Ubuntu 20.04.3 LTS

### JDK

Java: 22.0.1; OpenJDK 64-Bit Server VM 22.0.1+8-16

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

Product Version: Apache NetBeans IDE 22-rc1

### Are you willing to submit a pull request?

No

### PR DESCRIPTION
**Pull request by mbien**
Stack trace analyzer window:

 - module name part can go beyond java identifiers it seems

Maven stack trace output line matcher:

 - add compile class path to hyperlink logic in case the resource isn't in exec class path for some reason
 - other minor fixes

fixes #7385

### CODE REVIEW

File: java/maven/src/org/netbeans/modules/maven/api/output/OutputUtils.java [hunk 1]
```diff
@@ -263,9 +263,12 @@ protected ClassPath getClassPath() {
...
             if(prj != null) {
                 ProjectSourcesClassPathProvider prov = prj.getLookup().lookup(ProjectSourcesClassPathProvider.class);
+                // appending compile cp probably doesn't hurt although everything should be in exec cp already
                 return createProxyClassPath(
-                    Stream.concat(Stream.of(prov.getProjectClassPaths(ClassPath.EXECUTE)),
-                                  Stream.of(prov.getProjectClassPaths(ClassPath.BOOT)))
+                    Stream.of(Stream.of(prov.getProjectClassPaths(ClassPath.EXECUTE)),
+                              Stream.of(prov.getProjectClassPaths(ClassPath.COMPILE)),
+                              Stream.of(prov.getProjectClassPaths(ClassPath.BOOT)))
+                          .flatMap(s -> s)
```
Comment (mbien) [inline java/maven/src/org/netbeans/modules/maven/api/output/OutputUtils.java:271]: everything should be in the exec cp I think, but https://github.com/apache/netbeans/blob/139498df4577f8cfb1b6c76a1c30a4ca8002ea8b/java/maven/src/org/netbeans/modules/maven/classpath/ClassPathProviderImpl.java#L287 is difficult to debug due to all the lazy lambdas.

If tests have a module info (and src too), test sources seem to be missing atm.

**Comment by mbien** [comment]
for future reference:
there are at least three stack trace parser/linker impls:
 - [junit test runner tree](https://github.com/apache/netbeans/blob/139498df4577f8cfb1b6c76a1c30a4ca8002ea8b/java/java.testrunner.ui/src/org/netbeans/modules/java/testrunner/ui/api/UIJavaUtils.java#L86)
 - [stack trace analyzer window](https://github.com/apache/netbeans/blob/master/java/java.navigation/src/org/netbeans/modules/java/stackanalyzer/StackLineAnalyser.java)
 - [maven output trace linker](https://github.com/apache/netbeans/blob/139498df4577f8cfb1b6c76a1c30a4ca8002ea8b/java/maven/src/org/netbeans/modules/maven/api/output/OutputUtils.java#L175), [matcher](https://github.com/apache/netbeans/blob/139498df4577f8cfb1b6c76a1c30a4ca8002ea8b/java/maven/src/org/netbeans/modules/maven/execute/CommandLineOutputHandler.java#L98)
 - ...

**Review by matthiasblaesing — APPROVED** [review]
Looks sane to me and fixes the referenced problem. Thank you!

**Comment by mbien** [comment]
rebasing before merge
