### PR TITLE
Fix #8764 Gradle 9 ProjectDependency resolution to other project

### LINKED ISSUE #8764: NetBeans 27 gives error with Gradle 9 web project
### Apache NetBeans version

Apache NetBeans 27

### What happened

With Gradle 9 and a web app project (i.e. `apply plugin: 'war'`), NetBeans actually seems to work fine, _but_ continuously shows a project problem to be resolved. The description of this problem is  `org.gradle.api.Project org.gradle.api.artifacts.ProjectDependency.getDependencyProject()`.

Actually running `clean` and `build` tasks works fine on this project -- including from NetBeans. And I see no usages of this API, nor of any plugins beyond `war` and `maven-publish` is this project.

And now I notice the same issue actually on another app project using the latest `com.gradleup.shadow` plugin. And I see no usages of the API in question in my build -- and again the actual build runs just fine.

### Language / Project Type / NetBeans Component

Java Gradle Web App Project

### How to reproduce

I _think_ this is readily reproducible.

If not, then NetBeans at a minimum should provide better feedback here -- since the actual Gradle clean/build works AOK even from within NetBeans.  So it is utterly unclear exactly what is failing and from where, i.e. what is triggering execution of this obsolete Gradle API???

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11

### JDK

Java 21

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

_No response_

### Are you willing to submit a pull request?

No

### PR DESCRIPTION
**Pull request by wrprice**
In multi-project Gradle builds where one project depends on another project, for example:

    implementation project(':otherProject')

The dependency is represented in the Gradle API as a `ProjectDependency` object, but `ProjectDependency::getDependencyProject` was deprecated, and then removed in Gradle 9.0.0.  When using Gradle >= 9, it now requires two steps to resolve target of the dependency:

1. Use reflection to access `ProjectDependency::getPath` (added in Gradle 8.11)
2. Resolve the target project using `Project::findProject(String path)`

fixes #8764

---
**^Add meaningful description above**

<details open>
<summary>Click to collapse/expand PR instructions</summary>

By opening a pull request you confirm that, unless explicitly stated otherwise, the changes -

 - are all your own work, and you have the right to contribute them.
 - are contributed solely under the terms and conditions of the Apache License 2.0 (see section 5 of the license for more information).

Please make sure (eg. `git log`) that all commits have a valid name and email address for you in the Author field.

If you're a first time contributor, see the Contributing guidelines for more information.

If you're a committer, please label the PR before pressing "Create pull request" so that the right test jobs can run.

### PR approval and merge checklist:

1. [x] Was this PR [correctly labeled](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=240884239#PRsandYouAreviewerGuide-PRtriggeredCIJobs(conditionalCIpipeline)), did the right tests run? When did they run?
4. [x] Is this PR [squashed](https://cwiki.apache.org/confluence/display/NETBEANS/git%3A+squash+and+merge)?
5. [x] Are author name / email address correct? Are [co-authors](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors#creating-co-authored-commits-on-the-command-line) correctly listed? Do the commit messages need updates?
3. [x] Does the PR title and description still fit after the Nth iteration? Is the description sufficient to appear in the release notes?

If this PR targets the delivery branch: [don't merge](https://cwiki.apache.org/confluence/display/NETBEANS/Pull+requests+for+delivery). ([full wiki article](https://cwiki.apache.org/confluence/display/NETBEANS/PRs+and+You+-+A+reviewer+Guide))

</details>

### CODE REVIEW

File: extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java [hunk 1]
```diff
@@ -1562,6 +1563,23 @@ private void detectDependencies(NbProjectInfoModel model) {
...
+                    return dep -> {
+                        try {
+                            String path = (String) getPath.invoke(dep);
+                            return project.findProject(path);
+                        } catch (ReflectiveOperationException e) {
+                            throw new UnsupportedOperationException(e);
+                        }
+                    };
+                },
+                () -> ProjectDependency::getDependencyProject); // removed in Gradle 9
```
Comment (mbien) [inline extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java:1581]: IMO: this would be more future proof if we would call the new method directly and use reflection for the removed method. (basically the other way around)

@lkishalmi @sdedic do you think we can bump the gradle tooling version of this module so that we can call `getPath()` directly?

Comment (wrprice) [reply extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java:1581]: Gradle >= 8.11 but <9 should have both APIs

Comment (wrprice) [reply extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java:1581]: I have an alternative branch where I think I've done the necessary work to bump this module up to Gradle 8.11.1.  Tested locally on some personal Gradle projects using 7.5.x, 8.11-14, and 9.0.0 and they all open w/out error notifications. In the process there was a fun roadbump that turns out to be a JDK bug re: method references under certain conditions.

The 8.11.1 upgrade has several more required changes compared to this spot fix.  LMK how you'd like me to proceed.

Comment (mbien) [reply extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java:1581]: @wrprice sounds great! We could try to get this PR here in first, then see if we can bump the tooling version.

Last time I tried I could get a hello world project using gradle 5.x to build, but I believe 4 didn't work anymore. But I personally don't use gradle all that much, I let others comment on the versions question. NB generally tries to support lower versions if it is still reasonably maintainable while keeping up with latest releases.

> The 8.11.1 upgrade has several more required changes compared to this spot fix. LMK how you'd like me to proceed.

Once this PR here is merged, we could certainly take a look at the version bump proposal, unless there is a showstopper I am not aware of (cc @lkishalmi )

**Comment by mbien** [comment]
looks like the paperwork check doesn't like the commit header. The reason for that is because github added the `noreply` mail which isn't a valid address.  Its a [github settings](https://docs.github.com/en/account-and-profile/how-tos/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-on-github).

Assuming your local `git log` has the right email address on the commit, you will likely still have to make a change to this PR for the new setting to take effect. Feel free to do a `git pull --rebase https://github.com/apache/netbeans master` and then simply force push into your branch.


You can see if it is worked by looking at the patch file for this PR:

https://github.com/apache/netbeans/pull/8797.patch

**Comment by mbien** [comment]
@wrprice thanks for the fix and congrats on your first contribution!
